#!/usr/bin/env ruby
# frozen_string_literal: true

require "slop"
require "shellwords"

opts = Slop.parse suppress_errors: true do |o|
  o.banner = <<~HELP
    Execute a program and collect its socket traffic.

    Usage:
      wgotw [options] "<command [arg ...]>"

    Example:
      wgotw --verbose "curl http://example.com"
  HELP

  o.on "-h", "--help", "print this help message" do
    puts o
    exit
  end

  o.bool "-v", "--verbose", "display verbose output"
  o.bool "-D", "--debug", "display debugging output"
  o.bool "-d", "--devel", "run in devel mode (use libwgotw.so in the CWD)"
end

ENV["WGOTW_VERBOSE"] = "1" if opts.verbose?
ENV["WGOTW_DEBUG"] = "1" if opts.debug?
ENV["LD_LIBRARY_PATH"] = ".:#{ENV["LD_LIBRARY_PATH"]}" if opts.devel?

# better hope libwgotw is somewhere on the library search path!
ENV["LD_PRELOAD"] = "libwgotw.so #{ENV["LD_PRELOAD"]}"

if opts.args.first.nil?
  puts opts
  exit
end

cmdline = Shellwords.split(opts.args.first)

exec(*cmdline)
